{% set name = "loop-rate-limiters" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 589218f978421debe221eeadf4de3e64cff8c34c58bbaeb878e6326490f4f370

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - flit >=2,<4
  run:
    - python >=3.8

test:
  imports:
    - loop_rate_limiters
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://pypi.org/project/loop-rate-limiters/
  summary: Loop rate limiters.
  dev_url: https://github.com/upkie/loop-rate-limiters
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
